[package]
name = "patseeker"
version = "0.1.0"
edition = "2024"

[lib]
name = "seek"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.42"
mockall = "0.13.1"
rust_decimal = { version = "1.39.0", features = ["macros"] }
